### ISSUE TITLE
Usage of translation.jl example

### ISSUE THREAD

**Issue by TravisA9** [FluxML/Flux.jl#10]
I have been testing out and playing with the Flux examples to get a feel for how things work. I'm particularly interested in the translation.jl example but noticed this disclaimer:

> Note that this model excercises some of the more advanced parts of the compiler and isn't stable for general use yet.

 I tried running it anyway just to see what would happen and didn't see any results. I do have a question though about the input. I do not see any input source specified there but then there are a few details i'm not familiar with. Is more needed to make this example work?

**Comment by MikeInnes** [comment]
Yes, a bit more is needed for this example beyond input data; I got this more-or-less working a while back as a test case, but haven't kept it going as things have moved around, and need to rework the recurrence APIs generally.

I'll try to get this working over the next couple of weeks so that it's usable.

**Comment by MikeInnes** [comment]
A little bit more than a couple of weeks, but I've updated the [translation example](https://github.com/FluxML/model-zoo/blob/master/phonemes/1-model.jl) in the model zoo. Let me know how you get on with it.
