### ISSUE TITLE
Layers and Params should support equality

### ISSUE THREAD

**Issue by oxinabox** [FluxML/Flux.jl#1012]
For testing purposes I wanted to check if two models were identical.
(Making sure I was doing the right thing with my seeds)

Right now there is no easy way to do this.
See what I tried: (these tests are using on old version

```
julia> Random.seed!(1);

julia> x = Dense(10,10)
Dense(10, 10)

julia> Random.seed!(1);

julia> y = Dense(10,10)
Dense(10, 10)

julia> x==y
false

julia> params(x)
Params([Float32[0.052575205 0.44167045 … -0.44290894 0.115914196; 0.34975964 -0.0914253 … 0.08449556 0.14750573; … ; 0.2187416 0.2876231 … 0.108851254 0.32387242; 0.074596524 0.13426614 … -0.2106525 0.4129367], Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])

julia> params(x) == params(y)
false

julia> params(y)
Params([Float32[0.052575205 0.44167045 … -0.44290894 0.115914196; 0.34975964 -0.0914253 … 0.08449556 0.14750573; … ; 0.2187416 0.2876231 … 0.108851254 0.32387242; 0.074596524 0.13426614 … -0.2106525 0.4129367], Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])

julia> collect(params(y)) == collect(params(x))
true
```

**Comment by ven-k** [comment]
I tried to implement the same using functions,  which didn't work.

function modelEquality(a, b)
    c = ConvRunner(a)
    d = ConvRunner(b)
    return collect(params(c)) == collect(params(d))
end

function ConvRunner(a)
    Random.seed!(1)
    f = a
    return(f)
end

Placing Random.seed! inside modelEquality instead of ConvRunner didn't help either. Trying to use macro only worsens the matter. I think this is because we are already building the model and using Random.seed! inside does not affect. (PS: whenever I passed a, b which was created after preceding each with Random.seed! modelEquality returned true)

A workaround would be to **read the meta info of both parameters passed and reconstruct the conv layers inside modelEquality**. (I couldn't find enough details on this in docs. Please **direct me**) or a simpler way would be checking typeof() each layer and compare. Like this

function modelEquality(a::Any, b::Any)
    return typeof(a) == typeof(b)
end

But does this defeat the purpose?

**Comment by GHTaarn** [comment]
An even more simplified example of this is:

m = Dense(3,4)
a = params(m)
b = params(m)
a == b

This returns false.

In my opinion this does not follow the Julia guidelines for == and should therefore be considered a bug. Personally I am not affected by this right now as I only ran into this while debugging my code and have found my bug, but it would be nice to get it fixed because the more water tight Flux is the better.

For Julias guidelines I am referencing https://docs.julialang.org/en/v1/base/math/#Base.:== and https://stackoverflow.com/questions/38601141/what-is-the-difference-between-and-comparison-operators-in-julia

**Comment by dnabanita7** [comment]
According to this [PR](https://github.com/FluxML/Zygote.jl/pull/622), the comparison is order based now. Can I work on this issue?

**Comment by CarloLucibello** [comment]
`==` for `Params` is implement in recent Zygote versions
