### ISSUE TITLE
Metal GPU acceleration on Apple Silicon

### ISSUE THREAD

**Issue by BooBSD** [FluxML/Flux.jl#1304]
Hello,

I have a question.
Do you plan to support Metal GPU acceleration on Apple Silicon in future?

Thank you.

**Comment by jpsamaroo** [comment]
See my answer to a this question at https://github.com/FluxML/Flux.jl/pull/938#issuecomment-703179045

**Comment by Eugleo** [comment]
Sorry for being ignorant; does that mean that once you get Flux working with AMD GPUs, support for Metal will come with it?

**Comment by jpsamaroo** [comment]
No, it will not. Apple's Metal stack is completely separate from AMD's ROCm stack, so it will require a full new implementation in Julia (see https://github.com/JuliaGPU/Metal.jl).

**Comment by Eugleo** [comment]
I’ve seen this, I’m not sure whether it’s under active development (last commit in Nov), and what it (at least roughly) means time-wise for Flux on Apple Sillicon. Is it months away? Or more than a year? The readme doesn’t say much beyond “only interesting to developers”.

**Comment by ToucheSir** [comment]
Flux on Apple silicon is a different topic altogether. The library has worked on Rosetta for a while, and (depending on the state of native ARM support in base Julia) may work natively too.

My understanding of the timeline on Metal.jl is "expect nothing, unless you can contribute for find a way to get us proper development resources". Remember that getting the base library working is only the _first_ part of getting it working with Flux. You may have to write an entire NN kernel lib from scratch since I'm not sure apple provides one for GPU.
