### ISSUE TITLE
how to use `flatten` layer? (it does not flatten arrays)

### ISSUE THREAD

**Issue by phineas-pta** [FluxML/Flux.jl#1525]
hello, I'm playing with the MNIST dataset, and surprise: the `flatten` layer does not flatten array 😮 

here an example:

```julia
julia> using Flux

(@v1.5) pkg> status Flux
Status `~/.julia/environments/v1.5/Project.toml`
  [587475ba] Flux v0.11.1

julia> x = [[1, 2] [1, 2]]
2×2 Array{Int64,2}:
 1  1
 2  2

julia> Flux.flatten(x)
2×2 Array{Int64,2}:
 1  1
 2  2

julia> reshape(x, :)
4-element Array{Int64,1}:
 1
 2
 1
 2
```

I don't know if this is right way to use it though 😕 

Thanks

**Comment by darsnack** [comment]
`flatten` will flatten all dimension except the last. This is because the last dimension is generally treated as the batch dimension. You can see the equivalent reshape code in the [docstring](https://fluxml.ai/Flux.jl/stable/models/layers/#Flux.flatten). Hope this helps!

Please re-open the issue if you feel there's an unaddressed bug, or the docs could be improved.

**Comment by phineas-pta** [comment]
thank you for your response

I'm playing with MNIST dataset, so when I pass an image through `flatten`, it does nothing then next layer throws error 😢 

so I suppose to write my own flatten function in that case then

**Comment by darsnack** [comment]
That's not necessary. If you want to pass in a single image at a time, you can just add a batch dimension:
```julia
julia> x = rand(28, 28, 1);

julia> xbatch = reshape(x, size(x)..., 1);

julia> size(xbatch)
(28, 28, 1, 1)
```

**Comment by ToucheSir** [comment]
In fact, this reshape operation is so common that Flux exposes a built-in utility for it. See https://fluxml.ai/Flux.jl/stable/utilities/#Flux.unsqueeze

**Comment by darsnack** [comment]
Sounds like your images are WIDTH x HEIGHT (MNIST is only a single color channel). You will need to add two extra dimensions — one for channels and another for batch.
```julia
julia> using Flux
[ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]

julia> x = rand(28, 28);

julia> size(Flux.unsqueeze(x, 3))
(28, 28, 1)

julia> size(Flux.unsqueeze(Flux.unsqueeze(x, 3), 4))
(28, 28, 1, 1)
```

**Comment by phineas-pta** [comment]
I'm sorry, the docs doesn't have a clear example so I'm not really sure what I'm doing

so for example I have a code like this

```julia
julia> import Flux

julia> train_images = float.(Flux.Data.MNIST.images()); # convert grayscale to float

julia> train_labels = Flux.Data.MNIST.labels();

julia> test_images = float.(Flux.Data.MNIST.images(:test)); # convert grayscale to float

julia> test_labels = Flux.Data.MNIST.labels(:test);

julia> model = Flux.Chain(
           Flux.flatten,
           Flux.Dense(28^2, 128, Flux.NNlib.relu),
           Flux.Dropout(.2),
           Flux.Dense(128, 10),
           Flux.NNlib.softmax
       )
Chain(flatten, Dense(784, 128, relu), Dropout(0.2), Dense(128, 10), softmax)

julia> model(train_images)
ERROR: DimensionMismatch("matrix A has dimensions (128,784), matrix B has dimensions (1,60000)")
```

so I have to do `Flux.unsqueeze(train_images, 3)` then?

**Comment by ToucheSir** [comment]
`Flux.Data.MNIST.images` returns actual image structs and not arrays. If you just want the raw data arrays/tensors (which is what most people do), I would install [MLDatasets](https://github.com/JuliaML/MLDatasets.jl) and use the code in the README there.

**Comment by darsnack** [comment]
`Flux.Data` is going to deprecated anyways. MLDatasets.jl is preferred like @ToucheSir said.

Currently, `train_images` is a 1D array of 2D arrays. The first level of arrays is each image sample. The second level is the image itself which is 28x28. The first error you got is because you did not broadcast your model (you tried to evaluate an array of images instead of evaluating each image at a time). You fixed this by doing your second example, but then you got an error because of the `unsqueeze` issue. Doing `Flux.unsqueeze.(train_images, 3)` will add a third dimension to each image that represents a batch size of 1.

For examples, please refer to the [model zoo](https://github.com/FluxML/model-zoo). If you still face issues, I suggest using [Discourse](https://discourse.julialang.org) to ask questions. You'll get more responses on that forum which is specifically designed for questions instead of Github which is more suited to bug reports/feature requests.

**Comment by phineas-pta** [comment]
ok thank you guys `model zoo` is so much better, I went all over the place to look for an example
