### ISSUE TITLE
Flux.normalise vs standardise

### ISSUE THREAD

**Issue by luboshanus** [FluxML/Flux.jl#1541]
Hi,

I have been using Flux and its inner function `Flux.normalise` in its meaning to transform a variable that it follows`N(0,1)`. However, it seems natural it might be confusing since I would call this `standardise` and as normalization, one could have normalized variable on the range `[0,1]`.

Thus, it leads that normalise would be 
`x_normalised = (x .- minimum(x)) ./ (maximum(x) - minimum(x))`
and 
`x_standardised = (x .- mean(x)) ./ std(x)`.

Thanks for considering. Or if I am missing something, just close this.

**Comment by ToucheSir** [comment]
Normalization is a bit of an overloaded term and I don't believe min-max scaling should be the default meaning. Flux likely uses standardization by default because some of the norm layers use it as a helper function (a cursory glance shows layernorm and possibly more). Since Flux depends on StatsBase, it's probably better to use https://juliastats.org/StatsBase.jl/stable/scalarstats/#Z-scores-1 anyhow.
