### ISSUE TITLE
Fallback implementation convolution when using Duals

### ISSUE THREAD

**Issue by cdsousa** [FluxML/Flux.jl#1598]
I had posted a question to Slack about having performant convolutions when using `Zygote.ForwardDiff.Dual`s types in convolutions.
Dhairya told me to post this MWE I made here:
```julia
import Flux
import Zygote
arr = Zygote.ForwardDiff.Dual{Nothing, Float32, 1}.(rand(Float32, 10,10,1,1))
weight = Zygote.ForwardDiff.Dual{Nothing, Float32, 1}.(rand(Float32, 3,3,1,1))
bias = Zygote.ForwardDiff.Dual{Nothing, Float32, 1}.(rand(Float32, 1))
convol = Flux.Conv(weight, bias)
convol(arr)
```
warns with
```
┌ Warning: Slow fallback implementation invoked for conv!  You probably don't want this; check your datatypes.
│   yT = ForwardDiff.Dual{Nothing, Float32, 1}
│   T1 = ForwardDiff.Dual{Nothing, Float32, 1}
│   T2 = ForwardDiff.Dual{Nothing, Float32, 1}
└ @ NNlib C:\Users\xxxxxx\.julia\packages\NNlib\ev8gq\src\conv.jl:206
```
even though the datatypes are all equal.

**Comment by darsnack** [comment]
`NNlib.conv` will hit the fallback method if either to two conditions are met:
1. The weight, bias, and input types do not match
2. The type is not a supported [GEMM data type](https://github.com/FluxML/NNlib.jl/blob/908ec40d9b8b78fff66b8a88209abc78e168110d/src/gemm.jl#L24).

So, the current behavior is the expected behavior. Of course, there are cases (e.g. dual numbers) where this may not be desirable. The difficulty is knowing when a wrapped numeric type can be "destructured" and "restructured" vs. when falling back is the correct thing.

I am not as familiar with the forward diff implementations as reverse diff. Should there not be a `ChainRules.frule` for `conv`? That seems like the most straightforward way to handle this.

**Comment by cdsousa** [comment]
Ok, I understand! I'll check whether there is some material about forward-differentiating a convolution. Thank you.

**Comment by DhairyaLGandhi** [comment]
Use Zygote.Forward? We could really use some testing of that.

**Comment by darsnack** [comment]
Isn't the above using `Zygote.ForwardDiff`?

**Comment by cdsousa** [comment]
Yes, it is using `Zygote.ForwardDiff`. I also tried using `Zygote.forward_jacobian` but had the same result.

**Comment by DhairyaLGandhi** [comment]
Both those use ForwardDiff, Zygote.Forward is different.

**Comment by darsnack** [comment]
Well the original example will "never" work. `Dual` should not directly pass into `NNlib.conv`. If you try to take a gradient with `Array{Float32}` using `ForwardDiff`, then the correct `frule` should be invoked to apply `conv` to the number and perturbation separately. So, `conv` is being called on `Array{Float32}`, then the rule restructures the results into a `Dual` array. This is just what I would expect.

**Comment by DhairyaLGandhi** [comment]
The message shows up because nnlib has its fast paths clearly defined for specific gemm eltypes, so that Duals would wind up in the generic path (giving the warning, and due to using forward mode without simd; poor performance)

**Comment by darsnack** [comment]
I know, that's exactly what I have said above 😉. I'm only pointing out that if the goal is to differentiate `conv` with forward diff, the original MWE should not occur, because the `frule` should operate `conv` on the components of the `Dual` array instead of just passing the array in directly.
