### ISSUE TITLE
Why does calling the gpu function not return an error when CUDA is unavailable

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/Flux.jl#1634]
Per the following code:
```Julia

julia> using CUDA

julia> CUDA.functional()
false

julia> m = Dense(10, 5)
Dense(10, 5)

julia> cpu(m)
Dense(10, 5)

julia> gpu(m)
Dense(10, 5)

julia> m
Dense(10, 5)

julia> CUDA.functional()
false
```
I would expect that when I call the GPU function on `m`, it would give an error given a GPU is not available to my understanding. Should there be a warn or print saying that it was not moved to the GPU? Otherwise, someone might think it was.

**Comment by ToucheSir** [comment]
I know some code in the wild assumes `gpu` will act as a no-op when CUDA isn't present, but we could definitely `@warn`. Thoughts?

**Comment by logankilpatrick** [comment]
Might be fair for more advanced users but personally I would assume things fail if I try to do that

**Comment by ToucheSir** [comment]
Erroring would be a breaking change, so hence I think warning would get us more mileage sooner. It would also be good to have a `to_device` function that still does fall back to CPU if/when `gpu` no longer does so.

**Comment by logankilpatrick** [comment]
Agreed!

**Comment by DhairyaLGandhi** [comment]
I would rather not create fragmentation of the api. Its pretty convenient to sprinkle GPU calls without assuming the environment before hand and running on the most appropriate hardware. Its pretty common in our pitches that `gpu` is a no-op and warning too often seems like extra noise when it's totally safe to make that call. Its also a nice to have to make code portable and generic. 

`to_device` would have the potential to confuse regarding its application since it would have to do something close to the current setup anyway. `device` is only known to be a GPU in specialised circles, so I'd want to do something like `to_device(m, :cpu)` to be clearer. But now things are less easily readable. Added the fact that you'll need to make the same change `cpu -> gpu` everywhere anyway.

**Comment by ToucheSir** [comment]
I don't really think we can get away from having a more explicit and complex interface eventually, especially for tasks like distributed training with multiple GPUs (where explicit device management is often necessary). `gpu` is also a bit of a poor name once you start factoring in other accelerators like TPUs. Ideally the function that offloads models to an accelerator when available should have a more accelerator-agnostic name,

**Comment by DhairyaLGandhi** [comment]
The name isn't specific to a `gpu` though. Torch.jl has a `torch` function that works exactly like `gpu` from the pov of an end user, but of course moves the arrays over for torch tensors. We should absolutely have a `tpu` analogue. Those are significantly more niche cases and therefore aren't going to be bundled with Flux, but one doesn't need to take a dep on Flux to implement such an API anyway (Functors.jl takes care of that).

Besides, working with DDP recently, I never once needed such a utility, even though I had to make changes to a few repos internally, the GPU/cpu was never a bottleneck. In fact, that part was the easy and reliable bit. 

`torch` (as most Torch.jl functions) also takes in a `device` kwarg which also isn't ideal ergonomics wise. Users wouldn't be interacting with this issue using Dagger or even CUDAs process based or task based multi-gpu support, since most of it is handled internally, behind the scenes. As long as you can show us how many devices can be used, the rest is handled for you.

**Comment by ToucheSir** [comment]
It's difficult to say what's niche or not, but I'd be willing to bet more DL practioners are using TPUs than ROCm or OneAPI-enabled GPUs :) Torch's `device` kwarg is indeed an eyesore, but the functionality it provides is still useful. I'm still of the opinion that `gpu` isn't a sub-optimal name for "run this on whatever accelerator is available". 

> one doesn't need to take a dep on Flux to implement such an API anyway (Functors.jl takes care of that)

One can also do `xpu = Flux.has_cuda[] ? gpu : cpu` :shrug:. I first saw that pattern in the wild, so it's not as if users always rely on `gpu` being a no-op. IMO the biggest argument around changing `gpu` is back compat and not that it's some local optimum in API design.

WRT DDP, it's worth noting that data parallel is just one approach in distributed training. Device placement is a _much_ bigger concern for model and pipeline parallelism because splitting a model is not the same as splitting a minibatch into even chunks. Part of the selling point of Flux is that it doesn't hide features behind multiple layers of abstraction and tries to keep the amount of magic to a minimum. I'm not sure we need to die on this hill of "no, you must let the framework handle device placement for you (or be a CUDA wiz and circumvent it)"

**Comment by DhairyaLGandhi** [comment]
Well use cases that optimise for device placement are very likely to need `CUDA.device` before they hit any issue with `gpu` so I don't know if that's any better. I personally don't agree that `gpu` being a substitute for "any accelerator" is a great idea. Its best to be clear, and while I would be fine with changing the *GPU* backend of `gpu` to mean CUDA/ROCm/oneAPI, I would think it would be nicer to have some degree of separation for TPUs/ Torch etc.

**Comment by ToucheSir** [comment]
> I personally don't agree that gpu being a substitute for "any accelerator" is a great idea. Its best to be clear, and while I would be fine with changing the GPU backend of gpu to mean CUDA/ROCm/oneAPI, I would think it would be nicer to have some degree of separation for TPUs/ Torch etc.

Just to be clear, I believe we're in agreement on this. The question at hand is if/how Flux should warn users who try to use gpu functionality without a GPU attached. Warning _once_ in `gpu` seems non-intrusive enough, but I'm not tied to it for this use-case.

**Comment by darsnack** [comment]
I feel like we're getting sidetracked from the core issue. A warning that prints only the first time you call `gpu` when `use_cuda` is false seems like a good idea. I doubt even an advanced user intentionally running code with `gpu` when no GPU is present would be bothered by that. And it goes a long way for beginners who might think their code is working and spend hours trying to figure out why `gpu` runs fine but all their weights are normal arrays.

**Comment by DhairyaLGandhi** [comment]
I mean, "I don't have a GPU, calling `gpu` did nothing" doesn't seem like a big leap. And if they do have a properly configured GPU then it would in fact do the conversion.

Also, that message would be displayed every time something or the other is moved to the GPU - mini batches, models, validation sets, test sets. 4 of them in the simplest possible case. Not to mention the extra time spent going through logging in the backwards pass.

**Comment by darsnack** [comment]
> a properly configured GPU

It's entirely possible to have a GPU and have it not functional. In fact, I have a server in my lab that constantly boots with the nvidia driver borked, and I constantly run into this issue. Only when I run smi do I realize the problem and have to reboot.

Also it's simple to set `maxlog=1`. Similar to #1636, this shouldn't be a big overhead on the backwards pass. At the very least, why can't we just try fixing something first, then reject it if it causes performance regressions?

**Comment by DhairyaLGandhi** [comment]
Well it's going to be a regression regardless. Its then also probably on
CUDA to have a warning on init.

**Comment by ToucheSir** [comment]
Since Flux unconditionally imports CUDA, it would be ideal if the first usage of actual CUDA functionality warned. Doesn't matter where/in which package that code lives as long as we can get the warning out.
