### ISSUE TITLE
Clear intermediate gradients between back! calls?

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#171]
I'm trying to do multiple, separate gradient calls before calling `opt()`. I thought I would be able to set the gradients of my params to 0 and call `back!` again, but the results aren't expected.

```
x = param([1.])
y= x+x # Demonstrating intermediate value
l = sum(y.^2)

Flux.back!(l)
@show x.grad # => [8.0] as expected
x.grad .= 0 # Clear the gradient.

Flux.back!(l) # Now I thought this would behave the same as above, but
@show x.grad # => [16.0]
```
I suppose this is because the gradient information isn't cleared from the `y` tracked term. How can I clear this gradient so each call to `back!` is distinct?

I'll need to be able to do this without explicitly naming and clearing all the intermediate variables.

**Comment by MikeInnes** [comment]
In this case it's just due to the gradient accumulated by `l`, i.e. `l.tracker.grad == 2`. If you set this back to `0` it'll work (in this case).

The easiest thing to do here is to use the functional interface:

```julia
julia> Tracker.gradient(x -> sum((x .+ x).^2), [1])
([8.0],)
```

Right now, Flux's AD is not designed to support intermediate variable reuse at all, so calling `back!` twice will break pretty much everywhere; you really need to recompute from scratch. (It may be possible to change that, however). The other option which is easy to do is to implement a `flush!` function that does the equivalent of `x.grad .= 0` over the whole graph.

**Comment by MikeInnes** [comment]
Or alternatively, I can just push the trivial fix to make this work :) So this will be fine on master now.

I'd still recommend `gradient` for clarity but your version will avoid doing the forward pass redundantly.

**Comment by jessebett** [comment]
Hey Mike,
I finally got around to using this and it's really nice. Thanks!
