### ISSUE TITLE
Flux.loadparams! is slow.

### ISSUE THREAD

**Issue by Gregliest** [FluxML/Flux.jl#1764]
According to the test case below, `Flux.loadparams!` is about 7x slower than creating a new Flux model and results in a lot more allocations. Is there a reason for that? The speed of `loadparams!` also seems to scale more poorly than creating a new model if more layers are added.

```julia
using Flux, BenchmarkTools

model = Chain(
  Dense(2, 3),
  Dense(3, 2),
  Dense(2, 2),
  Dense(2, 1)
)

p = Flux.params(model)

function buildModel(params)
  return Chain(
    Dense(params[1], params[2]),
    Dense(params[3], params[4]),
    Dense(params[5], params[6])
  )
end

@btime buildModel(p) # 691.101 ns (5 allocations: 224 bytes)
@btime Flux.loadparams!(model, p) # 4.963 μs (191 allocations: 7.08 KiB)
```

**Comment by ToucheSir** [comment]
`loadparams!` has to iterate through the entire model structure recursively because it calls `params`, so the additional time + allocations are expected: https://github.com/FluxML/Flux.jl/blob/460f0050374e69fad56dd11d0560fd060ed8b009/src/functor.jl#L58. Generally there shouldn't be a need to run it on any hot code path though, is there a reason you want to repeatedly call `loadparams!`?

**Comment by Gregliest** [comment]
Ok, that makes sense. I was thinking of using it in a Turing model to replace parameters when sampling stochastic weights, but I don't think that works with the gradient calculation.
