### ISSUE TITLE
How to get the mathematical expression of  Neural Network.

### ISSUE THREAD

**Issue by Runfa-Zhang** [FluxML/Flux.jl#1771]
In fact, the fully-connected neural network itself is a mathematical mapping, which can be expressed by a mathematical expression.

Not symbolic regression interpolation.

Neural network model is a mathematical expression. just return a  mathematical expression from neural network model in Julia.

**Comment by ToucheSir** [comment]
Not sure what your question is exactly, but here are a few possible answers:
1. If you're looking for how to translate between the mathematical formulation of NNs and code, I'd recommend course material on applied ML. https://mitmath.github.io/18337/ is a good one because it focuses on Julia specifically and talks about stuff like PINNs (which I gather you work with)
2. If you want to do symbolic manipulation of expressions in Julia instead of directly computing numeric results, have a look at the [JuliaSymbolics](https://juliasymbolics.org/) ecosystem.
3. If you still have questions, https://discourse.julialang.org/ (or, if you're more comfortable with the 中文版, https://discourse.juliacn.com) is the place to ask.

**Comment by Runfa-Zhang** [comment]
> Not sure what your question is exactly, but here are a few possible answers:
> 
> 1. If you're looking for how to translate between the mathematical formulation of NNs and code, I'd recommend course material on applied ML. https://mitmath.github.io/18337/ is a good one because it focuses on Julia specifically and talks about stuff like PINNs (which I gather you work with)
> 2. If you want to do symbolic manipulation of expressions in Julia instead of directly computing numeric results, have a look at the [JuliaSymbolics](https://juliasymbolics.org/) ecosystem.
> 3. If you still have questions, https://discourse.julialang.org/ (or, if you're more comfortable with the 中文版, https://discourse.juliacn.com) is the place to ask.

thanks so much！

**Comment by Runfa-Zhang** [comment]
# Many thanks for your help
