### ISSUE TITLE
Incompatibility with SpecialFunctions 2.0

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1802]
Cannot install latest Flux along side SpecialFunctions 2.0. There is no compat constraint in Flux, so we need to track where the conflict lies.

**Comment by cossio** [comment]
Relevant: https://github.com/JuliaMath/SpecialFunctions.jl/issues/364

**Comment by devmotion** [comment]
Many packages are not compatible with SpecialFunctions yet (most prominently maybe ForwardDiff, the PR is ready but there are some other unrelated and unreleased changes on the master branch which I was not sure how to deal with). There's no need to rush here though since SpecialFunctions 2 only removed a very old type piracy but does not contain any new features or other bug fixes.

**Comment by devmotion** [comment]
This issue should be fixed by the upcoming Zygote release: https://github.com/JuliaRegistries/General/pull/51051

**Comment by cossio** [comment]
Indeed, now I got SpecialFunctions 2.0 together with Flux 0.12.8.
