### ISSUE TITLE
Optimisers epsilon

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1818]
Why is epsilon defined as a global constant like this, https://github.com/FluxML/Flux.jl/blob/fe803a1a706eb7ecbbf46f7c7e6c20b01847146d/src/optimise/optimisers.jl#L6 ?

Given that it affects the behavior of the optimisers, I think it should be a parameter of each optimiser.

This would also allow users to modify its value, if they need to.

If people agree I can make a PR that makes epsilon a property of each optimiser.

**Comment by DhairyaLGandhi** [comment]
we could make it so it's a parameter. Since one is likely to use one (maybe two?) Optimisers for most cases it's not likely to interfere much but makes it so our api expands for every optimiser.

Are there cases where we would need to set `eps` per optimiser? I can maybe understand if it causes unexpected promotion with different number types.

**Comment by cossio** [comment]
I have seen some (rare) cases where people use a different value of epsilon and this helps with training stability.

Please see https://github.com/FluxML/Flux.jl/pull/1819.

**Comment by darsnack** [comment]
It is a parameter in Optimisers.jl already. We could add it to current Flux.
