### ISSUE TITLE
`Parallel` layer behaves diffferently in a `Chain` than on its own

### ISSUE THREAD

**Issue by nworb-cire** [FluxML/Flux.jl#1919]
This works correctly:
```julia
julia> Parallel(vcat, identity, identity)(rand(3), rand(2))
5-element Vector{Float64}:
 0.5439504030019264
 0.3395899415511118
 0.14283863174000977
 0.9384967481769869
 0.4598522005497009
```
But wrapping the layer in a `Chain` gives an error (whereas this is perfectly fine with other layer types, e.g. `Dense`):
```julia 
julia> Chain(Parallel(vcat, identity, identity))(rand(3), rand(2))
ERROR: MethodError: no method matching (::Chain{Tuple{Parallel{typeof(vcat), Tuple{typeof(identity), typeof(identity)}}}})(::Vector{Float64}, ::Vector{Float64})
Closest candidates are:  (::Chain)(::Any) at ~/.julia/packages/Flux/qAdFM/src/layers/basic.jl:49
```
The expected behavior can be recovered by wrapping the inputs as a tuple:
```julia
julia> Chain(Parallel(vcat, identity, identity))((rand(3), rand(2)))
5-element Vector{Float64}:
 0.4150097569277802
 0.8132277787994605
 0.5430711573747946
 0.7387009928008393
 0.3973824843995234
```
but requiring a different input structure in these two circumstances is not ideal.

Flux v0.12.9 on Julia 1.7.2

**Comment by ToucheSir** [comment]
> whereas this is perfectly fine with other layer types, e.g. `Dense`

That's because most layers take only a single input. c.f. `Binlinear` which has a similar "problem".

If it helps, you can either a) consider the vararg case a pure syntactic nicety when working with these layers outside of a container like `Chain`, or b) consider the tuple case an addon in order to interop with container layers. In either case, this is an artifact of language-level semantics around varargs/return values, not Flux layers (and certainly not `Parallel`, if any layer is "responsible" then it'd be `Chain`).
