### ISSUE TITLE
Simple chaining compatibility check

### ISSUE THREAD

**Issue by alex-s-gardner** [FluxML/Flux.jl#2017]
It seems incompatible layer chaining should throw an error., e.g. 

```
model = Chain(
    Dense(1, 1, σ),
    Dense(2, 1, identity)
)
```

 Is there a good reason not to throw an error in this case?

**Comment by ToucheSir** [comment]
There are two main challenges here:
1. Given an arbitrary combination of layers, how would you check for compatibility without the user providing some example input (or at least input size, as one does current with `Flux.outputsize`)?
2. Slicing a `Chain` [returns a `Chain`](https://github.com/FluxML/Flux.jl/blob/master/src/layers/basic.jl#L68-L69), and we don't want too much overhead on that path.

**Comment by alex-s-gardner** [comment]
Could we not at least check the connections between layers? A layer that outputs one value can not be chained with a layer that accepts 2 inputs... or maybe I'm still missing something.

**Comment by darsnack** [comment]
For just `Dense` layers, it's easy, because the output size is known like you mentioned. But for example, `Chain(Conv((3, 3), 3 => 16), flatten, Dense(512 => 10))` is still a very simple and basic example, but it is not possible to verify compatibility without getting the input size from the user.

So, it might make more sense to include some utility (e.g. `verify_structure(model, input_size)`) that takes in additional information instead of making the `Chain` constructor error on a small set of cases.

**Comment by mcabbott** [comment]
There is `outputsize`: 
```julia
julia> model = Chain(
           Dense(3 => 4, σ),
           Dense(5 => 6, identity)
       );

julia> Flux.outputsize(model, (3,))
┌ Error: layer Dense(5 => 6), index 2 in Chain, gave an error with input of size (4,)
└ @ Flux ~/.julia/packages/Flux/KkC79/src/outputsize.jl:107
ERROR: DimensionMismatch: matrix A has dimensions (6,5), vector B has length 4
```
