### ISSUE TITLE
[Discussion]: documentation for `@reexport`ed and `import`ed (or `using`) packages

### ISSUE THREAD

**Issue by Saransh-cpp** [FluxML/Flux.jl#2038]
The `Flux` namespace imports a lot of packages - some of them have their separate pages in `Flux`'s documentation, whereas some of them don't, and currently, there isn't a single rule for such packages.

The packages available under `Flux`'s namespace - 
- `Optimisers.jl`: has a separate section in `Flux`'s docs and a stand-alone documentation
- `NNlib.jl`: has a separate page in `Flux`'s docs and should have stand-alone documentation soon (see https://github.com/FluxML/NNlib.jl/pull/431)
- `OneHotArrays.jl`: recently added, `Flux`'s docs have not been updated, stand-alone docs are not deployed, is blocking #2035
- `MLUtils.jl`: has a separate page in `Flux`'s docs and a stand-alone documentation
- `Functors.jl`: has a separate page in `Flux`'s docs and a stand-alone documentation
- `Zygote.jl`: has stand-alone documentation and bits and pieces scattered over `Flux`'s documentation

I don't think we should remove these separate pages from Flux's documentation, but these pages should not do the job of the documentation of these independent packages.

We can either have separate pages detailing some of the functionalities provided by the package that would be of interest to Flux users (for example see the latest commit of #2035) or display the API reference of this package (for example, see https://fluxml.ai/Flux.jl/stable/models/nnlib/).

How should such documentation exist? Open for discussion :)

**Comment by darsnack** [comment]
I think the rule should be that every package has its own documentation. Flux should have pages (API + tutorials) on the packages it imports / exports functionality from.

**Comment by mcabbott** [comment]
Yes to every package having its own.

If Flux has a section per package, how much should these include? E.g. should they all include the full API (re-using exactly the same page as their own docs?) or should it be a subset (e.g. because half of NNlib exists to back Flux layers, which should be the focus?).

**Comment by Saransh-cpp** [comment]
Additionally, should these pages have a separate section in Flux's documentation (something like "Reexported packages"), or should they be mixed within different sections (like they are right now)?

And then the sidebar title and the page title -

(simply the package's name ("NNlib") or something like "[One-Hot Encoding with OneHotArrays.jl](https://fluxml.ai/Flux.jl/dev/data/onehot/#One-Hot-Encoding-with-OneHotArrays.jl)")

![image](https://user-images.githubusercontent.com/74055102/184612634-4b7386fe-6c54-4893-8020-6332c23bfd89.png)

**Comment by darsnack** [comment]
I think it's better to have separate pages but keep the pages next to other sections that make sense (e.g. NNlib belongs with model stuff, OneHotArrays belongs with data stuff). Keep in mind that there will still be an ecosystem page where we can specifically note the re-exported packages in a centralized place.

As far as what to export, I would say it depends on the library. NNlib should probably get all the public docstrings in a single API page, since many people (especially from other frameworks) might come to the Flux docs looking for the "functional" layers. MLUtils probably does not need everything re-documented, just things related to batching and `DataLoader`. On the other hand, MLUtils does deserve a tutorial page on an "intro to data loading" directly in the Flux docs, but I can't see any reason NNlib needs a tutorial page for anything.

**Comment by Saransh-cpp** [comment]
> On the other hand, MLUtils does deserve a tutorial page on an "intro to data loading" directly in the Flux docs

There is a tutorial (or more precisely, a getting-started/how-to guide) on `DataLoader` available here - https://fluxml.ai/tutorials/2021/01/21/data-loader.html. Should this be shifted to the new "Getting Started" section?
