### ISSUE TITLE
v0.13.5 breaks Flux.train! on a custom type

### ISSUE THREAD

**Issue by simonmandlik** [FluxML/Flux.jl#2045]
Hi, in [Mill.jl](https://github.com/CTUAvastLab/Mill.jl) we have a special matrix type we call [PostImputingMatrix](https://github.com/CTUAvastLab/Mill.jl/blob/master/src/special_arrays/postimputing_matrix.jl), which fills in a vector trainable parameters ψ when they are missing in the input data. In short:

```julia
julia> using Flux, Mill

julia> A = Mill.PostImputingMatrix(reshape(1:9, 3, 3))
3×3 PostImputingMatrix{Int64, Base.ReshapedArray{Int64, 2, UnitRange{Int64}, Tuple{}}, Vector{Int64}}:
W:
 1  4  7
 2  5  8
 3  6  9

ψ:
 0
 0
 0

julia> B = Mill.maybehotbatch([1, missing, 3], 1:3)
3×3 MaybeHotMatrix with eltype Union{Missing, Bool}:
  true  missing    ⋅
   ⋅    missing    ⋅
   ⋅    missing   true

julia> A * B
3×3 Matrix{Int64}:
 1  0  7
 2  0  8
 3  0  9
```

For efficiency, this requires several some [custom `rrule`s](https://github.com/CTUAvastLab/Mill.jl/blob/23b5f66d6677d2cc3e15fec5f06ad8604732013c/src/special_arrays/postimputing_matrix.jl#L100-L119) as well as [`opt`ing out of default rules for Base.*](https://github.com/CTUAvastLab/Mill.jl/blob/23b5f66d6677d2cc3e15fec5f06ad8604732013c/src/special_arrays/postimputing_matrix.jl#L71).

When taking parameters and computing gradients, in `Flux@v0.13.4` it works as follows:

```julia
julia> Flux.params(A)
Params([PostImputingMatrix(W = [1 4 7; 2 5 8; 3 6 9], ψ = [0, 0, 0])])

julia> gradient(() -> sum(A*B), Flux.params(A)).grads
IdDict{Any, Any} with 2 entries:
  3×3 PostImputingMatrix => (W = [1 0 1; 1 0 1; 1 0 1], ψ = [1, 1, 1])
  :(Main.A)              => (W = [1 0 1; 1 0 1; 1 0 1], ψ = [1, 1, 1])
```

that is, `Flux.Params` contain the whole struct, `Zygote` returns structured gradients as well, and the only thing remaining for gradient descent is providing custom [`Flux.update!`](https://github.com/CTUAvastLab/Mill.jl/blob/23b5f66d6677d2cc3e15fec5f06ad8604732013c/src/special_arrays/special_arrays.jl#L100-L107).

In `Flux@v0.13.5` the same calls give:

```julia
julia> Flux.params(A)
Params([[1 4 7; 2 5 8; 3 6 9], [0, 0, 0]])

julia> gradient(() -> sum(A*B), Flux.params(A)).grads
IdDict{Any, Any} with 3 entries:
  :(Main.A)             => (W = [1 0 1; 1 0 1; 1 0 1], ψ = [1, 1, 1])
  [0, 0, 0]             => nothing
  [1 4 7; 2 5 8; 3 6 9] => nothing
```

`Flux.Params` no longer contain the whole struct and, consequently, gradients are not assigned to correct ids in the gradient Dict. This obviously will break many things such as updating parameters when training.

This is fixable by e.g. redefining `Flux.params` so that it behaves like in 0.13.4, or fixing the `gradient` call, which is probably a Zygote thing. But what is a preferable way to work with composite types like this one for the future?

I have posted an identical issue to `Zygote` as well, let me know and I will delete one.

**Comment by mcabbott** [comment]
The culprit is https://github.com/FluxML/Flux.jl/pull/2007, which changes `params` to test `Functors.isleaf` before accepting.

With both old & new versions, Functors thinks this A has two children:
```julia
julia> Functors.functor(A)  # from @functor
((W = [1 4 7; 2 5 8; 3 6 9], ψ = [0, 0, 0]), Mill.var"#134#135"())

julia> Optimisers.trainable(A)  # default method
(W = [1 4 7; 2 5 8; 3 6 9], ψ = [0, 0, 0])
```
I haven't looked closely at this use. But it feels like a bit of a bug for `params` and `trainable` to have been doing different things. What gets updated during training, just `ψ` or both fields?

**Comment by simonmandlik** [comment]
In the example, where `eltype(B)` is `Union{Missing, Bool}`, we want to update both fields. If `eltype(B)` would be only `Bool` (no missing values in `B`), then `ψ` won't get into action and will have no gradient, and, analogically for the case when `eltype(B)` is just `Missing`.

**Comment by darsnack** [comment]
The issue is that #2007 introduced an additional check that anything included in `Params` is a `Functor.isleaf`. Your array type is not since it has been `@functor`'d.

I believe the old behavior of not recursing any `AbstractArray{<:Number}` is a bug...the condition to be included in `Params` should be whether something is trainable or not, and just `AbstractArray{<:Number}` does not capture it. That being said, the new check does not seem right. The leaf nodes according to Functors is a superset of trainable parameters. It should stop recursion when the trainable subset is empty, not when the set of all leaves is empty. With the correct check in place, the fix here on Mill.jl's side will be to define `trainable(::PostImputingMatrix) = (;)`

Separately, this change does break things, but only things that relied on buggy behavior (up to interpretation). Strictly speaking, it is not a breaking change, but I don't know if we ought to be more cautious.

**Comment by mcabbott** [comment]
Yes I think I agree the `params` check is too wide, it should follow `trainable`. 

But in this case, it sounds like `trainable` is correctly pointing at both fields. Returning `(;)` ought to prevent either from being updated.

What I don't see here yet is why that doesn't just work. Why doesn't training just happen on the leaf nodes? The issue is `[1 4 7; 2 5 8; 3 6 9] => nothing`, whereas ideally Zygote should have worked out the gradient with respect to this parameter. I guess the `rrule` which returns a `Tangent` is not further explored in implicit mode?

**Comment by darsnack** [comment]
I think the issue is that for updating, `PostImputingMatrix` should be treated as a leaf, because there is a custom `update!`. Recursing it breaks this. At the same time, in a non-training context, it should be recursed, e.g. for `gpu`.

**Comment by mcabbott** [comment]
Ok. This is possible. It's not a use of `trainable` we (or at least I) thought of before -- you want to stop the recursion while still treating the *container* as trainable, while the usual use case is to mark which *children* are contain trainable arrays, which are always `isleaf`.

Another option might be: If this thing is to be thought of as an array (which happens to have fields Flux shouldn't know about) then it should be a leaf type. To make `gpu` work, it should overload `adapt_structure` to recurse further into it.

**Comment by simonmandlik** [comment]
We needed custom `rrule`s for efficiency and that's basically it. Every other customization that is in the code (opting out of `rrule` for `Base.*`, custom `update!`, etc...) just seemed necessary for the whole thing to work, but we will gladly get rid of them. So I see two possible solutions:

1. In the ideal world, `Zygote` would compute gradients as expected

```julia
julia> gradient(() -> sum(A*B), Flux.params(A)).grads
IdDict{Any, Any} with 3 entries:
  :(Main.A)             => (W = [1 0 1; 1 0 1; 1 0 1], ψ = [1, 1, 1])
  [0, 0, 0]             => [1, 1, 1]
  [1 4 7; 2 5 8; 3 6 9] => [1 0 1; 1 0 1; 1 0 1]
```

and no custom `update!` would be needed. This would mean fewer overloads, but requires `Zygote` to fix this.

2. Just regress to the behavior in 0.13.4 by adding one more overload `Flux.params(::PostImputingMatrix) ...`.

The first option looks cleaner to me

**Comment by ToucheSir** [comment]
> 1. In the ideal world, `Zygote` would compute gradients as expected...and no custom `update!` would be needed. This would mean fewer overloads, but requires `Zygote` to fix this.

Zygote does this already, as can be seen if you called `gradient(A -> sum(A*B), A)` instead. The reason it doesn't work after #2007 is because Flux was way too liberal about what could be considered a leaf node in a model in the past.

In that light, the best way to address this is to tell Flux `Mill.PostImputingMatrix` should be treated as a whole array instead of being decomposed into individual pieces. There are two ways to do this:
1. Don't `@functor PostImputingMatrix` and instead override the [Adapt interface](https://github.com/JuliaGPU/Adapt.jl/) to allow it to still work with `cpu/gpu/f32/f64`. Adapt is already an indirect dependent of Mill, so you're not taking on unnecessary load time with this.
2. Keep the functor declaration, but override `trainable` as [mentioned above](https://github.com/FluxML/Flux.jl/issues/2045#issuecomment-1222435499). This can also be done without taking on extra deps, because `trainable` is defined in Optimisers.jl and Mill -> Flux -> Optimisers.

I suspect you'd want to do one of these either way, because it does not seem like updating the individual components of `PostImputingMatrix` is correct and Optimisers.jl (becoming the default in Flux 0.14) will absolutely do this since the existing definition says (via `@functor`) that `.W` and `.ψ` should be handled separately.

**Comment by simonmandlik** [comment]
Going with the 1., this fixes the `params` issue, however, I still need custom `update!`, is that correct?

```julia
julia> using Adapt

julia> Adapt.@adapt_structure PostImputingMatrix

julia> ps = Flux.params(A)
Params([PostImputingMatrix(W = [1 4 7; 2 5 8; 3 6 9], ψ = [0, 0, 0])])

julia> gs = gradient(() -> sum(A*B), ps)
Grads(...)

julia> opt = Flux.Descent()
Descent(0.1)

julia> Flux.update!(opt, ps, gs)
ERROR: MethodError: no method matching vec(::NamedTuple{(:W, :ψ), Tuple{Matrix{Int64}, Vector{Int64}}})
Closest candidates are:
  vec(::LinearAlgebra.Transpose{<:Number, <:AbstractVector}) at ~/.julia/juliaup/julia-1.8.0+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:219
  vec(::LinearAlgebra.Adjoint{<:Real, <:AbstractVector}) at ~/.julia/juliaup/julia-1.8.0+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:220
  vec(::SparseArrays.AbstractSparseVector) at ~/.julia/juliaup/julia-1.8.0+0.x64/share/julia/stdlib/v1.8/SparseArrays/src/sparsevector.jl:965
  ...
Stacktrace:
 [1] restructure(x::PostImputingMatrix{Int64, Base.ReshapedArray{Int64, 2, UnitRange{Int64}, Tuple{}}, Vector{Int64}}, y::NamedTuple{(:W, :ψ), Tuple{Matrix{Int64}, Vector{Int64}}})
   @ ArrayInterfaceCore ~/.julia/packages/ArrayInterfaceCore/7kMjZ/src/ArrayInterfaceCore.jl:476
 [2] update!(opt::Descent, x::PostImputingMatrix{Int64, Base.ReshapedArray{Int64, 2, UnitRange{Int64}, Tuple{}}, Vector{Int64}}, x̄::NamedTuple{(:W, :ψ), Tuple{Matrix{Int64}, Vector{Int64}}})
   @ Flux.Optimise ~/.julia/packages/Flux/EXOFx/src/optimise/train.jl:16
 [3] update!(opt::Descent, xs::Zygote.Params{Zygote.Buffer{Any, Vector{Any}}}, gs::Zygote.Grads)
   @ Flux.Optimise ~/.julia/packages/Flux/EXOFx/src/optimise/train.jl:24
 [4] top-level scope
   @ REPL[22]:1
 [5] top-level scope
   @ ~/.julia/packages/CUDA/DfvRa/src/initialization.jl:52
```

**Comment by darsnack** [comment]
You need to implement `ArrayIntereface.restructure` for your array type as well.

**Comment by simonmandlik** [comment]
Thank you, I presume something like this would be enough for cases when both fields have nonzero gradients

```julia
function ArrayInterface.restructure(x::PostImputingMatrix, y)
    PostImputingMatrix(ArrayInterface.restructure(x.W, y.W), ArrayInterface.restructure(x.ψ, y.ψ))
end
```

but what if one of these is `nothing`? Is there a better way than replacing with `zero(x.W)` and `zero(x.ψ)`?

**Comment by ToucheSir** [comment]
This is an interesting case and something I hadn't thought of before, thanks for bringing it up. I agree that having to use `zero` is less than optimal here, so the question is what minimal changes could make this work without it.

Perhaps an acceptable short-medium term solution is to overload `Flux.Optimise.update!`:
```julia
function update!(opt::AbstractOptimiser, x::PostImputingMatrix, x̄)
  update!(opt, x.W, x̄.W)
  update!(opt, x.ψ, x̄.ψ)
end
```
Longer-term, we hope to remove `params` entirely in Flux 0.14. Then this issue will no longer be relevant. I recognize that you can't ask all your users to switch off implicit params overnight, however, so it's on us to make sure workarounds like the above continue functioning until folks have had time to migrate :slightly_smiling_face:

**Comment by simonmandlik** [comment]
I see, thank you all very much for help :)
