### ISSUE TITLE
Using users provided weight matrix to build LSTM layers

### ISSUE THREAD

**Issue by Chengfeng-Jia** [FluxML/Flux.jl#2130]
### Describe the potential feature

In this [demo](https://fluxml.ai/Flux.jl/stable/models/layers/#Flux.Dense) for Dense layer, user can use provided weight matrix to build Dense layer. `d1 = Dense(ones(2, 5), false, tanh)`. When I want to build a RNN/LSTM layer, it failed `Lstm = Flux.LSTMCell(W2_1,W2_2,b2,s2_1)
Lstm(data[1])`.￼

The above W2_1,W2_2,b2,s2_1 are pre-defined random weight matrix. The error is `MethodError: objects of type Flux.LSTMCell{Matrix{Float64}, Vector{Float64}, Vector{Float64}} are not callable`

**Comment by Chengfeng-Jia** [comment]
The above W2_1,W2_2,b2,s2_1 are pre-defined random weight matrix. The error is `MethodError: objects of type Flux.LSTMCell{Matrix{Float64}, Vector{Float64}, Vector{Float64}} are not callable`

**Comment by ToucheSir** [comment]
The state you initialize the LSTMCell with needs to be a 2-tuple of `AbstractMatrix` (e.g. `(ones(1, 1), zeros(1, 1)`) and not a single array as you described. Otherwise https://github.com/FluxML/Flux.jl/blob/b26113df68c4d186996f515826ae8f7727b2fd4e/src/layers/recurrent.jl#L308 won't work. You can see how the main constructor does this initialization in https://github.com/FluxML/Flux.jl/blob/b26113df68c4d186996f515826ae8f7727b2fd4e/src/layers/recurrent.jl#L302-L303.

**Comment by Chengfeng-Jia** [comment]
Thank you so much! It works.
