### ISSUE TITLE
"failed to start primary task" with Julia 1.9 and nthreads(:interactive) > 0

### ISSUE THREAD

**Issue by MarkusSchildhauer** [FluxML/Flux.jl#2257]
Reproducible on Julia 1.9 with:
```
julia --threads 2,1 -e "using Flux"  
┌ Error: failed to start primary task
└ @ FoldsThreads.Implementations ~/.julia/packages/FoldsThreads/aWnRU/src/root_spawners.jl:34
ERROR: InitError: TaskFailedException

    nested task error: BoundsError: attempt to access 2-element Vector{Union{Nothing, Channel{Any}}} at index [3]
    Stacktrace:
     [1] setindex!
       @ ./array.jl:969 [inlined]
     [2] (::FoldsThreads.Implementations.var"#29#31")()
       @ FoldsThreads.Implementations ~/.julia/packages/FoldsThreads/aWnRU/src/root_spawners.jl:62
     [3] macro expansion
       @ ~/.julia/packages/FoldsThreads/aWnRU/src/utils.jl:6 [inlined]
...
```
It's caused by the dependency [FoldsThreads](https://github.com/JuliaFolds/FoldsThreads.jl) and reported [here](https://github.com/JuliaFolds/FoldsThreads.jl/issues/21#issue-1705831796) but there is no response so far. 
I cannot estimate how critical this is.

**Comment by mcabbott** [comment]
Can reproduce. I think Flux depends on this [via MLUtils](https://github.com/JuliaML/MLUtils.jl/blob/main/Project.toml#LL12C1-L12C13) hence may move the issue. 

I believe that some JuliaFolds packages are being moved to https://github.com/JuliaFolds2/ to deal with otherwise unfixable maintenance issues. There isn't a version of FoldsThreads there but perhaps something else can be changed... maybe @MasonProtter knows?

**Comment by MarkusSchildhauer** [comment]
I opened it now on [MLUtils](https://github.com/JuliaML/MLUtils.jl/issues/158), too.

**Comment by ToucheSir** [comment]
Opening a duplicate issue won't help drive things along, just create more work for maintainers. The best way to make progress is to find the root cause of the issue and create a MWE for it so that the FoldsThreads maintainers can do something about it. Even better would be submitting a PR fix for it.

**Comment by mcabbott** [comment]
I've heard that TKF had to leave the building for a bit. FoldsThreads2 is, if I understand right, the work-around for others not having the right permissions to fix things. So it may be necessary to e.g. change MLUtils to use one of those, or to move another package across to the new org.

**Comment by CarloLucibello** [comment]
where is FoldsThreads2?

**Comment by mcabbott** [comment]
Sorry I mean JuliaFolds2, and all its sub-packages.
