### ISSUE TITLE
Allow old silent behavior for `gpu`

### ISSUE THREAD

**Issue by darsnack** [FluxML/Flux.jl#2293]
### Motivation and description

As suggested by @IanButterworth on Slack, Flux used to support an "advanced" behavior for `gpu` where it would silently use the CPU if no GPU was available. This meant that code could run on CPU or GPU (CUDA) systems with no changes.

We determined this behavior was a foot gun and added a warning 0.13. It would be nice to preserve the old functionality when explicitly requested.

### Possible Implementation

We can implement `gpu(x; warn = true)` as the default case. All the warnings are defined in `src/functors.jl` so it seems like it is fairly easy to support this. There are some redundant versions of this warning in the CUDA extension, but I think those can be safely removed.

**Comment by mcabbott** [comment]
The warning is only once, right?

One idea would be to allow `Flux.gpu_backend!("CPU")` or "none" or `nothing`. That would (I propose) both silence any such warnings, and also mean `gpu` still does nothing even if you (or some other package) loads CUDA later.

**Comment by darsnack** [comment]
True that's a better implementation.

**Comment by IanButterworth** [comment]
The way it's been used in ObjectDetector is passively.
```
using ObjectDetector
yolomod = YOLO.v3_COCO()
batch = emptybatch(yolomod)
results = yolomod(batch)
```
If a gpu is available it uses it. `gpu` isn't exposed to the user.

I'm not against adding a kwarg to control it
```
yolomod = YOLO.v3_COCO(use_gpu=true)
```

And for that I'd add an internal convenience function something like
```
gpu(x, use::Bool) = use ? Flux.gpu(x) : x
```

**Comment by CarloLucibello** [comment]
I think we should adopt the solution recently implemented in [Lux](https://github.com/LuxDL/LuxDeviceUtils.jl/blob/main/src/LuxDeviceUtils.jl) and create a "device" object as follows instead of using `gpu`:
```julia
device = Flux.get_device() #  1. If `gpu_backend` preference is set and the backend is functional on the system, then
                                              #   that device is selected.
                                              #  2. Otherwise, check the loaded modules and select a gpu device accordingly
                                              #  3. If no GPU device is functional fall back on CPU

model = model |> device
batch = batch |> device
```
This pattern has a few advantages:
- we have automatic selection of the backend
- we can customize the behavior of the data movement once and for all, compared to passing options to `gpu`
- data movement is type stable
- we can think of future extension, e.g. select one among different CUDA devices

**Comment by codetalker7** [comment]
Hello everyone. I'm trying to implement the idea by @CarloLucibello, i.e using `device` objects instead of the GPU function. I have created a draft PR for this: https://github.com/FluxML/Flux.jl/pull/2297.  I have mentioned a few pointers in the TODO list, which I'll soon complete. The draft contains the main high level idea along with some examples.

Can someone look at the PR? Also, this is my first time contributing to Flux, so apologies if I haven't followed any contribution guidelines.
