### ISSUE TITLE
Flux.testmode!() should disable gradient tracking

### ISSUE THREAD

**Issue by staticfloat** [FluxML/Flux.jl#232]
As discussed on slack a while back, the typical Flux evaluation incantation of:

```
testmode!(model, true)
y_hat = mapleaves(Flux.Tracker.data, model)(feature_mat)
testmode!(model, false)
```

Should probably be shortened somehow.  We can fold the `mapleaves()` call into `testmode!()` perhaps by having `testmode!()` return the baked `model`, and telling the user to use that new baked model instead.

**Comment by MikeInnes** [comment]
You could shorten this a bit to:
```
predict = mapleaves(Flux.Tracker.data, model)
testmode!(predict, true)
```

And then you can call `predict(x)` wherever you need to – it also stays tied to the original model, so you can save the `mapleaves` call. Even the `mapleaves` will go away with #86 since models will be non-tracking by default.

Until then I'd be happy to have a simple out-of-place `testmode` function that does both things at once.

**Comment by MikeInnes** [comment]
Pleasingly, with #643 this all becomes a no-op.
