### ISSUE TITLE
Flux.setup buggy and broken in latest v.0.13.17

### ISSUE THREAD

**Issue by rcherukuri12** [FluxML/Flux.jl#2394]
All documentation and training code examples are broken and don't work.( on apple silicon )

I switched back to using Ignite.jl approach 
It just works

May be the Flux.jl package experts can look at what "elegance" is and switch to Ignite.jl and adopt it ?

**Comment by mcabbott** [comment]
Note that v0.13.17 is quite far from the latest, released 17 Jun 2023. This may mean you have ancient versions of some packages... I would try `] add Flux@0.14.13` before anything else.

Then, can you post what errors you see, say from this http://fluxml.ai/Flux.jl/stable/models/quickstart/ ? Without a stack trace it's very hard to guess. 

https://github.com/jondeuce/Ignite.jl looks neat, but appears to be at a higher level -- its example still calls `setup(Adam(1f-3), model)` so that has to work first.

**Comment by rcherukuri12** [comment]
Thank you ...I switched and was able to run. Flux.setup(...) was the one that was blowing up in that version.
Now I have to go back and see if I can run ReinforcementLearning.jl

closing this issue.

**Comment by rcherukuri12** [comment]
updated version works.
