### ISSUE TITLE
Dense layers with shared parameters 

### ISSUE THREAD

**Issue by pagnani** [FluxML/Flux.jl#2432]
Dear all

Suppose I have the following (trivial) encoder/decoder network. I want the decoder's parameters to be shared with the encoder (or more precisely the transpose of it):

```
using Flux, Statistics
import CUDA

function prepare_model(nin,nout,M,B; device=cpu)
    enc = Dense(nin=>nout) |> device
    dec = Dense(transpose(enc.weight))
    model = Chain(enc,dec) 
    loss(x,m) = mean(abs2,x-m(x))
    opt = Adam()
    Z = rand(Float32,nin,M) |> device
    data = Flux.DataLoader(Z,batchsize=B,shuffle=true)
    return model, data,loss,opt,Z
end
```

If I build the model on CPUs, I get the correct behavior (the 2 weights of both encoder and decoder are the same ... see the `===`)

```
julia> model_cpu, data_cpu, loss, opt, Z_cpu = prepare_model(5,6,1024,128, device=Flux.cpu);
julia> model_cpu.layers[1].weight === model_cpu.layers[2].weight'
true
```

Now if I build the model on GPUs,  as from the `prepare_model` method is doing it is ok:

```
julia> model_gpu, data_gpu, loss, opt, Z_gpu = prepare_model(5,6,1024,128, device=Flux.gpu);
julia> model_gpu.layers[1].weight=== model_gpu.layers[2].weight'
true
```
And now the problem. Suppose that now send to the GPU the model in this way:
```
julia> model_gpu_wrong = Flux.gpu(model_cpu)
Chain(
  Dense(5 => 6),                        # 36 parameters
  Dense(6 => 5),                        # 35 parameters
)                   # Total: 4 arrays, 71 parameters, 688 bytes.

julia> model_gpu_wrong.layers[1].weight === model_gpu_wrong.layers[2].weight'
false
```
So it seems that gpu-ing the entire network in one shot seems to lose track of the parameter's sharing.

Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 40 × Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, broadwell)
  Threads: 47 on 40 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 32

The driver version is a bit outdated but I do not have gpus available with more recent NVIDIA Drivers to test.
```
julia> CUDA.driver_version()
v"11.0.0"
```

**Comment by jondeuce** [comment]
This seems like a bug. `Flux.gpu(model_cpu)` should be roughly equivalent to

```julia
julia> model_gpu_wrong = Flux.fmap(CUDA.cu, model_cpu; exclude = Flux.isleaf);
julia> model_gpu_wrong.layers[1].weight === model_gpu_wrong.layers[2].weight'
true # works
```

which works, because `Flux.isleaf(::Transpose)` returns `false`, and so the parent array will only be moved to the GPU once. So you can use this as a workaround for now.

The bug arises because Flux actually uses the internal function `Flux._isleaf` defined here

https://github.com/FluxML/Flux.jl/blob/285145aa59ef0fb1478c3c5d618a25c75f0b258c/src/functor.jl#L184-L189

in the call to `fmap` here

https://github.com/FluxML/Flux.jl/blob/285145aa59ef0fb1478c3c5d618a25c75f0b258c/ext/FluxCUDAExt/functor.jl#L56

and this fails, because `Flux._isleaf(::Transpose)` returns `true` due to the definition of `_isbitstype(x)` above, and so both the parent array and its transpose get moved to the GPU separately:

```julia
julia> model_gpu_wrong = Flux.fmap(CUDA.cu, model_cpu; exclude = Flux._isleaf); # note: using Flux._isleaf now
julia> model_gpu_wrong.layers[1].weight === model_gpu_wrong.layers[2].weight'
false # fails
```

The `_isbitsarray(x)` check is too broad. Probably needs to happen lower down in Functors.jl somewhere.

**Comment by pagnani** [comment]
Thanks @jondeuce for the suggestion. BTW also the reverse (i.e. GPU -> CPU) fails

```
julia> model_gpu, data_gpu, loss, opt, Z_gpu = prepare_model(5,6,1024,128, device=Flux.gpu);
julia> model_gpu.layers[1].weight === model_gpu.layers[2].weight'
true
julia> model_cpu = cpu(model_gpu);
julia> model_cpu.layers[1].weight === model_cpu.layers[2].weight'
false
```
Again, following (almost) blindly your suggestion, 
```
julia> model_cpu = fmap(x -> Flux.adapt(Flux.FluxCPUAdaptor(), x), model_gpu, exclude = Flux.isleaf);
julia> model_cpu.layers[1].weight === model_cpu.layers[2].weight'
true
```
solves the issue.

**Comment by jondeuce** [comment]
Makes sense that the reverse direction fails, too, since `_isbitsarray(x)` (and therefore `_isleaf(x)`) has the same pitfall for any `AbstractArray`.

This needs to be fixed and some tests added. I'm not sure if it should be done in Flux.jl or Functors.jl. The only shared parameters tests I see in Flux.jl are [this one](https://github.com/FluxML/Flux.jl/blob/285145aa59ef0fb1478c3c5d618a25c75f0b258c/test/utils.jl#L561) and [these ones](https://github.com/FluxML/Flux.jl/blob/285145aa59ef0fb1478c3c5d618a25c75f0b258c/test/loading.jl#L123), which don't test that moving tied weights to another device preserves the tie.

**Comment by jondeuce** [comment]
Here's a MWE to reproduce the bug:

```julia
using Flux, CUDA

function mwe()
    x = rand(1)
    m = (; a = x, b = x')
    @assert m.a === m.b' # passes
    mgpu = m |> gpu
    @assert mgpu.a === mgpu.b' # fails
end
```
