### ISSUE TITLE
Easier way of switching models from cpu to gpu?

### ISSUE THREAD

**Issue by philtomson** [FluxML/Flux.jl#298]
I notice from the docs that if you want to use gpu you call a _gpu()_ function on the matrices to wrap. I think the _gpu_ call is used in place of the _param_ call (or _cpu_ call).  I wonder if instead of having to change your model (where there might be many calls to _gpu_ needed) we might instead have two different namespaces, one for CPU and another for GPU. That way you'd only need to change one line of your script instead of potentially many lines.

It could work like:

`using Flux.GPU # for GPU`

or: 

`using Flux.CPU` 

where:

`using Flux`

would default to using Flux.CPU

**Comment by MikeInnes** [comment]
It's a bit tricky to do this in general, because you might do something like

```julia
weight = param(rand(5,5))
bias = rand(5) # i.e. this is a constant
```

In the first case we can happily inject the `gpu` into `param`, but in the second there's nowhere for us to do that.

The other issue with moving things automatically is that you may want to e.g. load a large dataset on the CPU and move each batch to the GPU one by one. So you often do need the explicit control.

You shouldn't generally end up with too many calls to `gpu`. If your model has many components, ideally you'd package these into a custom layer which can be moved around as a unit.

I'm generally not completely happy with the current situation either though, so I'm open to suggestions. I think what it'll take in general is a more advanced training harness setup, which takes more control over evaluation, distribution, data movement etc.

**Comment by darsnack** [comment]
I'm inclined to close this. Fine-grained control over what goes onto the GPU/CPU is a good thing and moving a model is not hard to do.
