### ISSUE TITLE
don't know how to handle argument of type Array{Float64,1}

### ISSUE THREAD

**Issue by merckxiaan** [FluxML/Flux.jl#318]
When I feed an image to a 147-element long Chain of `Conv` and `BatchNorm` layers, I get the following error:
`don't know how to handle argument of type Array{Float64,1}`. This error only occurs when using my gpu.
Does anybody know what I'm doing wrong?
Thanks, 
Jules

**Comment by CarloLucibello** [comment]
Are you trying to feed a vector to a convolutional layer? inputs are supposed to be 4d tensors

**Comment by merckxiaan** [comment]
Thanks, I believe my mistake was I didn't define the  image I fed in as a CuArray, once I did, however, I received the following error:
`CUDA error: out of memory (code #2, ERROR_OUT_OF_MEMORY)`
I don't believe my gpu doesn't have enough memory, it only has 3 GB but that should more than be enough to feed one image (416x416) through the model, shouldn't it?

**Comment by merckxiaan** [comment]
Nevermind,I clearly don't have enough memory, I overestimated my laptop :(

**Comment by MikeInnes** [comment]
We're working on checkpointing, which will make is easier to run models of essentially arbitrary size. Not totally ready yet though.

**Comment by merckxiaan** [comment]
@MikInnes I'm not sure I understand what checkpointing would do, would my gpu be able to offload data from calculations within a Chain? Would any gpu theoretically be able to run every model?
Thanks

**Comment by MikeInnes** [comment]
For backpropagation we essentially need to store all the intermediate results of the forward pass so that we can use them to calculate gradients in the backwards pass. Checkpointing is an intervention that tells Flux to recompute those values instead of storing them, so you can train a larger model at the expense of extra compute.

I'll close this in favour of an explicit issue for checkpointing – #402.
