### ISSUE TITLE
Do we need to check dimension compatibility when Chain is created?

### ISSUE THREAD

**Issue by johnnychen94** [FluxML/Flux.jl#373]
```julia
using Flux

c = Chain(Dense(10,5), Dense(2,1)) # It won't raise an error here

c(randn(10)) # raise an DimensionMismatch error here
```

I think it's better to check if dimensions of stacked layers are compatible when created. But to do this requires the information of valid-size for each kind of layer (including custom layer)

**Comment by MikeInnes** [comment]
Ideas are welcome here, but I suspect it's very hard to do this without making it a very special case for `Chain` of `Dense`.

OTOH I've opened #703 which I think addresses the underlying issue here.

I'll close this for now in favour of that one, but happy to reopen if there's something else we should do here.
