### ISSUE TITLE
Problem with the bias

### ISSUE THREAD

**Issue by patwa67** [FluxML/Flux.jl#483]
I wonder why the bias isn't picked up in my adaptation of the Housing example:
```
using Flux
using Flux: onehotbatch, onecold, mse, throttle
using Base.Iterators: repeated
using DelimitedFiles
using Statistics
using LinearAlgebra

cd(@__DIR__)

isfile("housing.data") ||
  download("https://raw.githubusercontent.com/MikeInnes/notebooks/master/housing.data",
           "housing.data")

rawdata = readdlm("housing.data")'

# The last feature is our target -- the price of the house.

x = rawdata[1:13,:]
y = rawdata[14:14,:]

# Normalise the data
x = (x .- mean(x,dims=2)) ./ std(x,dims=2)

# The model

m = Chain(
  Dense(13,1,identity))

loss(x, y) = mse(m(x), y)

dataset = repeated((x, y),1)
evalcb = () -> @show(loss(x, y))
opt = ADAM(params(m))

using Flux: @epochs
@epochs 100 Flux.train!(loss, dataset, opt, cb = throttle(evalcb,1))

params(m)[2]
```

**Comment by patwa67** [comment]
When you run the code ```params(m)[2] ``` becomes 0.09992487379894519. Shouldn't it be more like the mean of y, i.e. 22.52990099009901?

**Comment by MikeInnes** [comment]
Perhaps if you remove the normalisation step, but with that line the mean is 0 anyway.

**Comment by patwa67** [comment]
No, just take the mean of y and it is not zero. it is only the input that is normalized, the bias should be close to 22.5.

**Comment by MikeInnes** [comment]
In either case, the model is capable of reasonable output without a bias, and clearly isn't forced to produce output of mean 0 – which suggests that the mean of `y` is already represented in weight matrix. You could probably regularise somehow to force that information to turn up in the bias instead.

Since this is more of a question than a technical Flux issue, hope you don't mind if I refer you to Julia's [forum](https://discourse.julialang.org). You'll probably get a much better answer from there.
