### ISSUE TITLE
How to add new backend?

### ISSUE THREAD

**Issue by chengchingwen** [FluxML/Flux.jl#53]
Hi, I would like to add [Knet](https://github.com/denizyuret/Knet.jl) as backend. 
Could anyone give me some advise on how and where to start?

**Comment by MikeInnes** [comment]
As we discussed on gitter, Flux will soon have a pure-Julia mode so that this won't be necessary. You can check out the [preview examples](https://github.com/FluxML/model-zoo) (which will work if you `Pkg.checkout("Flux")`).

Will close this for now, but do let me know if you play around with that and have any issues – I'll help you get set up wherever I can.
