### ISSUE TITLE
Type piracy causing issues with ForwardDiff

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/Flux.jl#573]
Hi,

It seems that this type piracy https://github.com/FluxML/Flux.jl/blob/master/src/tracker/lib/real.jl#L106 is causing issues over in Turing.jl https://github.com/TuringLang/TuringTutorials/issues/20. MWE:
```julia
using ForwardDiff
using Flux.Tracker
ForwardDiff.Dual{Nothing, Real, 1}(ForwardDiff.Dual(1.0))
```

**Comment by MikeInnes** [comment]
I see the issue but this test case doesn't work even without Flux loaded. Can you provide one that does?

**Comment by mohamed82008** [comment]
My bad. Here is the correct one:
```julia
ForwardDiff.Dual{Nothing, Real, 1}(ForwardDiff.Dual(1.0, 1.0))
```

**Comment by MikeInnes** [comment]
Great, thanks -- pushed a fix.

**Comment by michaelboutros** [comment]
This isn't the same issue but is in the same ballpark so I thought I'd post here. I'm having trouble using ForwardDiff.derivative on a tracked function because of an unexpected type. A very simple example:

`β = param([10, 1])
y(x) = β[1] + β[2]*x
dy(x) = ForwardDiff.derivative(x -> Tracker.data(model(x)),x)

dy(3) # Should be β[2]`

The error I get is:

`ERROR: LoadError: MethodError: *(::Flux.Tracker.TrackedReal{Float64}, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##9#10")),Int64},Int64,1}) is ambiguous. Candidates:
  *(a::Flux.Tracker.TrackedReal, b::Real) in Flux.Tracker at /Users/michaelboutros/.julia/packages/Flux/8XpDt/src/tracker/lib/real.jl:94
  *(x::Real, y::ForwardDiff.Dual{Ty,V,N} where N where V) where Ty in ForwardDiff at /Users/michaelboutros/.julia/packages/ForwardDiff/okZnq/src/dual.jl:130
Possible fix, define
  *(::Flux.Tracker.TrackedReal, ::ForwardDiff.Dual{Ty,V,N} where N where V)`
