### ISSUE TITLE
params not working with LinearAlgebra.mul!

### ISSUE THREAD

**Issue by hughsalimbeni** [FluxML/Flux.jl#627]
The LinearAlgebra.mul! function does not seem to work with a param type. With the * function things work fine, however. Here is a MWE

```julia
using Flux

x1 = [1., 2, 3]
x2 = [1., 3, 3]

param(x1) * param(x2)'  # works

import LinearAlgebra
res = zeros(3, 3)
LinearAlgebra.mul!(res, param(x1), param(x2)')  # fails 
```
Is this expected behaviour? 

This has caused Distances.jl to break when using Flux.

**Comment by MikeInnes** [comment]
Yeah, this is expected. Ideally Distances.jl should be able to work with both mutable and immutable array types (this would be a problem for e.g. staticarrays as well).

**Comment by hughsalimbeni** [comment]
Thanks for this.

**Comment by aterenin** [comment]
Can I ask why this is expected? Neither `param(x1)` nor `param(x2)` are mutated by `LinearAlgebra.mul!` in this example. There are lots of examples within Julia where high-performance code uses mutating BLAS routines where the input arguments are not mutated.

**Comment by MikeInnes** [comment]
It's actually the output that's the issue. In order to get gradients of the inputs we still have to track the result, which we can't do when `res` is just a plain array.

You can do it in principle if `res` is another tracked array, but it's tricky to implement and not done yet.

Zygote will eventually make supporting mutation of this kind easy though, since the `Tracked`/`param` types will disappear.

**Comment by aterenin** [comment]
Ah, so the problem is that `zeros` is of type `Matrix{Float64}` whereas it needs to be of type `TrackedMatrix{Float64}` for the code to make sense to begin with. 

As an alternative, one could instead use `Matrix{TrackedReal{Float64}}`, which appears to make Distances.jl work. Are there any major downsides to just doing this?

**Comment by MikeInnes** [comment]
There's nothing outright wrong with it, but it's likely to be slower than just using matrix-level operations since we have to track through every scalar-level add and multiply. You'll also want to be a bit careful about converting back to `TrackedMatrix` where possible (for which you can use `Tracker.collect`). A patch to Distances.jl would be ideal but as a workaround it's totally fine.

**Comment by aterenin** [comment]
Ah, so mainly this is an issue with performance rather than correctness. How bad do you think the decrease will be?

Similarly, if one uses the same trick with, say, `cholesky`, does that mean that Julia reverts to some pure-Julia implementation of Cholesky rather than using fast BLAS routines? I guess it's Julia so perhaps this is still fast.

Myself and @hughsalimbeni are currently looking into implementing some Deep Gaussian Process models in Flux. Using Distances.jl as well as Distributions.jl for computations would save us a lot of time compared to having to code kernel matrices and multivariate normal expressions by hand.

It's too bad Zygote.jl is still early stage as it seems it'd resolve some of these issues. Param types are nice from a user perspective because they allow you to turn optimization on and off as needed, and it'd be nice to use them without type headaches like the ones here.

**Comment by MikeInnes** [comment]
The slowdown will depend a lot on different factors, but for a matmul or cholesky that would otherwise go through blas it could be orders of magnitude.

There are other folks interested in using Distributions.jl with Flux so that may get fixed soon. Other than that it might be worth a look at [Stheno](https://github.com/willtebbutt/Stheno.jl); Will is actively working on using Zygote with that so a lot of what you need may work already.
