### ISSUE TITLE
`collect` drops gradients

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#657]
```julia
julia> xs = param([1, 2, 3])
Tracked 3-element Array{Float64,1}:
 1.0
 2.0
 3.0

julia> collect(xs)
3-element Array{Float64,1}:
 1.0
 2.0
 3.0
```

**Comment by Sklan** [comment]
So, I looked into this. I figured this is a method call ambiguity between ```Base.collect``` and ```Tracker.collect```.  
```julia
julia> xs = param([1, 2, 3])
Tracked 3-element Array{Float64,1}:
 1.0
 2.0
 3.0

julia> collect(xs)
3-element Array{Float64,1}:
 1.0
 2.0
 3.0

julia> Tracker.collect(xs)
Tracked 3-element Array{Float64,1}:
 1.0
 2.0
 3.0
```
I tried to fix it by explicitly exporting collect and creating a type annotation
from
```julia 
collect(xs)
```
to
```julia
collect(xs::TrackedArray)
```
But turns out its a bit messy. Since there exists a function in array.jl in Base,
```julia 
collect(A::AbstractArray)
```
and given that 
```julia
julia> xs isa TrackedArray
true

julia> xs isa AbstractArray
true
```
So, before opening a pull request I wanted some input on how to correctly handle this.

**Comment by MikeInnes** [comment]
`Tracker.collect` is actually a separate function which behaves slightly differently. `Base.collect` should just be the identity function on TrackedArrays. You can fix that by remove `collect` from [this line](https://github.com/FluxML/Flux.jl/blob/d6cf116a740c2879ff04de95174d1528b7e43cd6/src/tracker/lib/array.jl#L76) and redefining it.

**Comment by gxyd** [comment]
Since Flux now uses Zygote, does this issue still makes sense?
