### ISSUE TITLE
CUDAnative

### ISSUE THREAD

**Issue by NiklasGustafsson** [FluxML/Flux.jl#682]
The following code snippet, which is adapted from the first example in the Flux README, doesn't make it all the way to printing "DONE." It blows up invoking the model on CUArrays.

```julia
using CUDAdrv, CUDAnative, CuArrays
using Flux

d1 = Dense(10,5,σ)
d2 = Dense(5,10)
l1 = LSTM(5,5)
l2 = LSTM(5,5)

model(x) = x |> d1 |> l1 |> l2 |> d2 |> softmax

X = randn(10,10)

@show model(X)

model(cu(X))

println("DONE")
```

**Comment by vchuravy** [comment]
The problem is that `Dense` and `LSTM` contain parameter data:

```
julia> d2 = Dense(5,10)
Dense(5, 10)

julia> dump(d2)
Dense{typeof(identity),TrackedArray{…,Array{Float32,2}},TrackedArray{…,Array{Float32,1}}}
  W: TrackedArray{…,Array{Float32,2}}
```

That means your call to `model` uses GPU data and then calls a matmul between the CPU and GPU.

```julia
using CUDAdrv, CUDAnative, CuArrays
using Flux

d1 = Dense(10,5,σ) |> gpu
d2 = Dense(5,10) |> gpu
l1 = LSTM(5,5) |> gpu
l2 = LSTM(5,5) |> gpu

model(x) = x |> d1 |> l1 |> l2 |> d2 |> softmax

X = randn(10,10)

@show model(X)

model(cu(X))

println("DONE")
```

This converts the model parameters to the GPU before doing anything. `Chain` etc allow you to composite layers and then only do one translation step.

**Comment by NiklasGustafsson** [comment]
Thank you, that works now. I'll just request a nice actionable error message for this.

**Comment by darsnack** [comment]
This is resolved, but please re-open if there are more concerns.
