### ISSUE TITLE
Slowdown with Conv on CPU in newer versions of Flux+NNlib: forward pass doesn't use all available threads anymore

### ISSUE THREAD

**Issue by bhvieira** [FluxML/Flux.jl#771]
I was working with `NNlib#ccc6dad` due to #700  
I recently moved to master and things appear to be working right now, but to my dismay performance got way worse. Anyone experienced that?

I'm training on CPU because it's a small problem with simple locally connected layers. Epochs ran in a few minutes before, but now they are way slower. Even the forward pass takes minutes to compute.

Now I'm stuck because I don't remember the compatible Tracker/Flux releases to rollback...

**Comment by KristofferC** [comment]
It would be helpful if you could give an example of the code that got slower (preferably as minimum as possible).

**Comment by bhvieira** [comment]
In my experience this was blazing fast before:

`Conv((415,), 1=>64, NNlib.leakyrelu)(zeros(172225, 1, 25))`

**Comment by bhvieira** [comment]
It's complicated because I'm using #446 on my end, and it used to allow a function overloading that's not possible anymore it seems, perhaps that's the cause. I'll have to investigate a bit more.

**Comment by bhvieira** [comment]
Seriously, an epoch was a couple minutes at worst, now it's been 2 hours and it hasn't run a single epoch yet.

**Comment by Tokazama** [comment]
I don't have any suggestions that relate to NNlib old vs new but I know that my resnet implementations have been pretty delicate. You may want to consider using Zygote instead of Tracker. The deep networks + tracking every change was killing my memory.

**Comment by bhvieira** [comment]
Thanks for the suggestion, I'll give Zygote a try soon.

**Comment by bhvieira** [comment]
I'm at a loss here, I downgraded to Flux#53875a8 (release tag v0.7.3) and now everything is blazing fast again. What gives?

**Comment by Sleort** [comment]
I'm having the same experience (while at the same time upgrading my computer, thus muddying the waters...). Before the new NNlib, using `Conv` like
```
using Flux
m = Conv((3,3),1=>1)
x = rand(Float32,10,10,1,10^6)
m(x)
```
 fired up all available threads, while now only one is used. 

(Btw: Ordinary matrix multiplication, say
```
using LinearAlgebra
x = rand(10000,10000)
x*x
```
is still using multiple threads, so all seems to be well with OpenBLAS)

**Comment by bhvieira** [comment]
Great, thanks for the info @Sleort 
So what has changed in the meantime? 🤔

**Comment by Sleort** [comment]
I'm not quite sure, but I know that the convolution code has been (more or less) completely rewritten in the new NNlib (by @staticfloat, I believe. Maybe he has an idea?).

**Comment by staticfloat** [comment]
It's most likely because of mixed datatypes in your model.  The previous NNlib would silently convert things to give homogenous datatypes because our convolution implementations didn't have a native way to mix and match datatypes, but after the rewrite we have more control; we have a naive convolution algorithm that can be much, much slower than the optimized versions, and is what is picked when you do things like have Float64 data being convolved with a Float32 kernel.  I suggest you ensure that the datatypes of your computation are all homogenous (most likely you just need to slap a `data = Float32.(data)` before you push it through the model).

If that still doesn't fix it, run a single minibatch of data through your model (both forward and backward pass) while capturing performance data, and then print it out:

```julia
using TimerOutputs, NNlib
TimerOutputs.enable_debug_timings(NNlib)

<run single batch of data forward and backward>

display(NNlib.to)
```

**Comment by Sleort** [comment]
But if you run my simple example from above,
```
using Flux
m = Conv((3,3),1=>1)
x = rand(Float32,10,10,1,10^6)
m(x)
```
`m.weight`, `m.bias`, and `x` all consist of `Float32` elements. It still only runs on one core (regardless of batch size). Is this to be expected?

**Comment by staticfloat** [comment]
Multithreading will not kick in for such a small matrix.  Increase the size to something more realistic, like a `100x100` image with 16 channels, and you'll see multiple cores in use.  The criteria for what size of problem will use a multithreading approach is complex, but it hasn't changed.  You can verify this by comparing your CPU utilization between the latest stable version of Flux, (`v0.8.3`) and an older version from before the `NNlib` rewrite (`v0.8.0` will do).  By running `pkg> add Flux@0.8.0` you can switch versions (I recommend doing this in a new project to avoid trashing your main installation).  You'll see that NNlib version 0.5.0 gets installed, which is from before the rewrite, and on my computer, the threading of such a small problem is still single-core, because the BLAS library does not think that multithreading can help with such a skinny matmul.

**Comment by bhvieira** [comment]
> It's most likely because of mixed datatypes in your model. The previous NNlib would silently convert things to give homogenous datatypes because our convolution implementations didn't have a native way to mix and match datatypes, but after the rewrite we have more control; we have a naive convolution algorithm that can be much, much slower than the optimized versions, and is what is picked when you do things like have Float64 data being convolved with a Float32 kernel. I suggest you ensure that the datatypes of your computation are all homogenous (most likely you just need to slap a data = Float32.(data) before you push it through the model).

I was suspecting this after reading through some comments on the NNlib overhaul. So yes, my data was `Float16`, and the weights are all `Float32`. Now I'm hitting all threads in the forward pass, but have to deal with some gradient errors. 

So I consider this resolved, thanks for the the input @staticfloat !

**Comment by bhvieira** [comment]
Wait, just reopened because I remember I could hit multithreading in the forward pass with Float16 data and Float32 weights

**Comment by KristofferC** [comment]
> Wait, just reopened because I remember I could hit multithreading in the forward pass with Float16 data and Float32 weights

Presumably because the Float16 data got promoted to Float32.

**Comment by bhvieira** [comment]
> Presumably because the Float16 data got promoted to Float32.

@staticfloat confirmed this on Slack, so I can close the issue. Thanks everyone!
