### ISSUE TITLE
Some confusion about the meaning of param

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#81]
The distinction between a parameter and a tracked parameter is not clear cut. For example functions like
`params`, `forparams`, `mapparams`  operate on any member of an object, being them TrackedArrays or not. 

On the other hand the function `param` is essentially a constructor for a TrackedArray. 

But not any parameter needs to be tracked, and some confusion may arise:
```julia
julia> type Linear; w; b; end

julia> Flux.treelike(Linear) #needed by params

# only one tracked member
julia> lin = Linear(Flux.param(rand(2,2)), zeros(2))
Linear(param([0.563915 0.232109; 0.461798 0.7487]), [0.0, 0.0])

# returning both the tracked and non-tracked member
julia> params(lin)
2-element Array{Any,1}:
 param([0.563915 0.232109; 0.461798 0.7487])
 [0.0, 0.0]      
```
One way out would be the following:
- leave `params` as it is. A parameter is generally something characterizing an internal state of a layer. 
- change `param` -> `track`  for creating `TrackedArray`s. 
- define `tracked` similarly to `params` but returning only tracked variables.
-  optional: change `opt=SGD(params(net))`  to `opt=SGD(tracked(net))` (also `opt=SGD(net)` may be convenient to have)

bye
C

**Comment by MikeInnes** [comment]
I agree this isn't totally consistent. The plan you've outlined is also completely reasonable, although I would also point to #86, the API changes that are upcoming once Cassette is ready; that will change some of the distinctions that currently exist.

For now what I've done is to (a) rename `mapparams` to `mapleaves` (and it maps over non-layers of the model, whatever they are), and (b) tweak `params` to return only `TrackedArray`s, so that `param` consistently means "trainable parameter". Hopefully that clears things up a bit while remaining forwards-compatible.

**Comment by MikeInnes** [comment]
Marking this fixed, but let me know if you spot other inconsistencies.
