### ISSUE TITLE
Layer initialization with predefined weights

### ISSUE THREAD

**Issue by tueboesen** [FluxML/Flux.jl#830]
It would be great if there was a way to instantiate the various layers (Dense,Conv,...) with predefined weights.

This is especially relevant for reversible networks, autoencoders, and convolutional network.
This is discussed to a small extend in https://github.com/FluxML/Flux.jl/issues/488, however I feel the issue is more fundamental.

I want some kind of way in which I can do something like this:

```

a = Conv(...)
b = ConvTranspose(...,a.weights) such that b and a share the same weights

```
I have tried to see whether I could make this myself, but so far it has proven beyond my Julia skills.

**Comment by bhvieira** [comment]
`Conv` and `ConvTranspose` layers accept weight arguments.

Relevant source code:

> https://github.com/FluxML/Flux.jl/blob/master/src/layers/conv.jl#L35
> https://github.com/FluxML/Flux.jl/blob/master/src/layers/conv.jl#L90

**Comment by tueboesen** [comment]
I looked at that, but as far as I can see, they do not accept weight arguments. They accept weight initializers, meaning that you can tell them which distribution to generate the weights with.
Note, I could very well be mistaken on this, and if I am, could you please show me a minimalistic example of how to use this?

**Comment by bhvieira** [comment]
It does work. See again the definition of `Conv` function.

    Conv(w::AbstractArray{T,N}, b::AbstractVector{T}, σ = identity; stride = 1, pad = 0, dilation = 1)

The line you linked is a dispatch that teaches `Conv` to comply when you tell it the kernel size, number of channels, etc. instead of supplying the weights, which is basically whats contained in a `Conv` type. Basically it says:

If user provides this functional form: `Conv(k::NTuple{N,Integer}, ch::Pair{<:Integer,<:Integer}, σ = identity; init = glorot_uniform,  stride = 1, pad = 0, dilation = 1)`, perform this: `Conv(param(init(k..., ch...)), param(zeros(ch[2])), σ, stride = stride, pad = pad, dilation = dilation)`

**Comment by tueboesen** [comment]
You are absolutely right, it does work!

```
a=Conv((3,3),3=>16)
b=Conv(a.weight,a.bias)
```

Thank you very much.

**Comment by bhvieira** [comment]
I was writing an example, but I'm glad you sorted it out already 😉

**Comment by bhvieira** [comment]
Here is it in case anyone comes across this:

This:

    Conv((3,3), 1=>32)

Is fundamentally equivalent to this

    Conv(param(Flux.glorot_uniform(3,3,1,32)), param(zeros(Float32, 32)))
