### ISSUE TITLE
RFC: overload `eltype` for models to get current type for precision?

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#843]
I'm wondering if it makes sense to overload `eltype` to get the current type, e.g

```jl
eltype(Dense(10, 10)) # Float32
```

but this will assume each building block using the same precision, does this make sense? I'm not sure if what would be the use case for mixed precision, if there is no use case, maybe we should just allow this?

**Comment by MikeInnes** [comment]
What's the use case for this?

Given that we want to treat any function as a model, it's hard to rely on any functionality being available other than `call`. Beyond that I'm also not sure what to do for something like `Chain`, I guess we'd have to create unions or widen. It's a fair bit of extra complexity unless there's something really compelling we can do with it.

**Comment by janEbert** [comment]
I've done the following until now:
```julia
T = eltype(model(x).data)  # this is new
out = zeros(T, some_size)
for _ in 1:1000
    out .+= model(x)
end
```
If you wanted to, you could even optimize the "redundant" model call away.

**Comment by MikeInnes** [comment]
If you know `some_size` then you're already storing some information about the model that isn't accessible from the model alone (short of calling it). So it seems like you could just pass `T` around as well.

Unfortunately `eltype` isn't a guarantee here either since you can e.g. pass `BigFloat`s into a model and get them back instead of `T`.
