### ISSUE TITLE
update! not working

### ISSUE THREAD

**Issue by yanivabir** [FluxML/Flux.jl#951]
I'm trying to use the update! function from the optimisers docs.

```
Pkg.installed()["Flux"]
v"0.10.0"

using Flux: update!
ERROR: UndefVarError: update! not defined
```

Any clues?

**Comment by appleparan** [comment]
You don't need to call `update!` anymore thanks to `Zygote`

From docs (Basic/Simple Models)

v0.9
```
using Flux.Tracker: update!

Δ = gs[W]

# Update the parameter and reset the gradient
update!(W, -0.1Δ)

loss(x, y) # ~ 2.5
```

v10.0
```
W̄ = gs[W]

W .-= 0.1 .* W̄

loss(x, y) # ~ 2.5
```

**Comment by appleparan** [comment]
However, it seems optimizer section needs to be updated.

**Comment by appleparan** [comment]
For Optimiser, use `Flux.Optimise.update!`

**Comment by yanivabir** [comment]
Just making sure since Flux.Optimise.update! has no documentation:

If I have my gradient calculated analytically, I would use Flux.Optimise.update! just as the old docs use update! - ie

```
Flux.Optimise.update!(opt, λ, λ_update)
```

?

Thanks!

**Comment by appleparan** [comment]
Yeap
https://github.com/FluxML/Flux.jl/blob/bdeb9c6d584668c7cef1ce71caf659d611c86d65/src/optimise/train.jl#L9-L11

**Comment by dhairyagandhi96** [comment]
You can find some references [here](https://fluxml.ai/Flux.jl/stable/training/optimisers/#Optimiser-Interface-1)

The update! call is orthogonal really, and you can call it as before.

**Comment by gabrevaya** [comment]
I found the error of this issue while testing the codes in from the [documentation](https://fluxml.ai/Flux.jl/stable/training/optimisers/), in which update! is imported as `using Flux: update!` instead of `using Flux.Optimise: update!`. So probably the documentation should be fixed. 

Similarly, when trying `θ = Params([W, b])`, Params is not found. Should we import Params from Zygote or use `θ = params(W, b)` as in the [Basics section](https://fluxml.ai/Flux.jl/stable/models/basics/#Taking-Gradients-1)?

Besides these tiny details, thanks a lot for the new release!! I've been waiting for it for a long time! :)
